title: Tarlan Ziyadov
description: |
  Do not hesitate to reach out via email or LinkedIn direct message to discuss how we might collaborate.
email: tarlan.ziyadov@hotmail.se
baseurl: ""
domain: tarlanziyadov.github.io
url: ""
linkedin_username: tarlan-z-9096729a
github_username: TarlanZiyadov

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-livereload
