title: Tarlan Ziyadov
description: |
  Do not hesitate to reach out via email or LinkedIn to discuss how we might collaborate.
email: tarlan.ziyadov@hotmail.se
baseurl: ""
domain: tarlanziyadov.github.io
url: ""
linkedin_username: tarlan-z-9096729a
github_username: TarlanZiyadov

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-livereload
  - jekyll-paginate

paginate: 5
paginate_path: "/posts/page:num"

header_pages:
  - index.html
  - softwares.markdown
  - about.markdown
